trigger:
  batch: true
  branches:
    include:
      - refs/tags/*
  paths:
    include:
      - scaler/*

pr: none

jobs:
  - job: DockerReleaseScanAndPush

    pool:
      vmImage: 'ubuntu-latest'

    variables:
      CONTAINER_REGISTRY: choreocontrolplane.azurecr.io
      REPOSITORY: choreoipaas/dp-keda-http-add-on-scaler
      TAG: $(Build.SourceVersion)

    steps:
      - task: Docker@2
        displayName: 'Build Docker Image'
        inputs:
          command: build
          containerRegistry: 'wso2choreo-control-plane-acr'
          repository: $(REPOSITORY)
          tags: $(TAG)
          Dockerfile: "scaler/Dockerfile"
          buildContext: "."
      - template: install/install-trivy.yaml@common-templates
      - script: |
          set -eo pipefail
          trivy image --exit-code 1 \
          --severity HIGH,CRITICAL \
          --no-progress \
          --ignorefile .trivyignore \
          "choreocontrolplane.azurecr.io/choreoipaas/dp-keda-http-add-on-scaler:$(TAG)"
      - task: Docker@2
        displayName: 'Push Docker Image'
        inputs:
          command: push
          containerRegistry: 'wso2choreo-control-plane-acr'
          repository: $(REPOSITORY)
          tags: $(TAG)
