resources:
  repositories:
    - repository: common-templates
      type: github
      name: wso2-enterprise/choreo-common-pipeline-templates
      endpoint: wso2-enterprise

trigger:
  batch: true
  branches:
    include:
      - main
  paths:
    include:
      - operator/*

pr: none

variables:
  - name: CONTAINER_REGISTRY
    value: choreocontrolplane.azurecr.io
  - name: REPOSITORY
    value: choreoipaas/dp-keda-http-add-on-operator
  - name: TAG
    value: $(Build.SourceVersion)

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: Docker@2
    displayName: "Docker Build"
    inputs:
      command: build
      Dockerfile: "operator/Dockerfile"
      buildContext: "operator"
      containerRegistry: "wso2choreo-control-plane-acr"
      repository: $(REPOSITORY)
      tags: |
        $(TAG)
  - template: install/install-trivy.yaml@common-templates
  - template: pr/trivy-scan.yaml@common-templates
    parameters:
      IMAGES:
        - $(CONTAINER_REGISTRY)/$(REPOSITORY):$(TAG)
  - task: Docker@2
    displayName: "Push Docker image"
    inputs:
      command: push
      containerRegistry: 'wso2choreo-control-plane-acr'
      repository: $(REPOSITORY)
      tags: |
        latest
        $(TAG)
  - template: update-image-in-cp-overlays.yml@common-templates
    parameters:
      DOCKER_IMAGE_LIST:
        - ${{ variables.CONTAINER_REGISTRY }}/${{ variables.REPOSITORY }}:$(APP_REVISION)
